
server:
  port: 8081

zuul:
  routes:
    api:
      path: /api/**
      url: http://127.0.0.1:8081



spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/apigateway?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 8750
    driver-class-name: com.mysql.jdbc.Driver

logging:
  config: classpath:logback-spring.xml

mybatis-plus:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml




